repos:
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.0
  hooks:
  - id: go-fmt
    name: "[go] fmt"
  - id: go-mod-tidy
    name: "[go] tidy"

- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.1.6
  hooks:
  - id: shellcheck
    name: "[shell] check"