---

name: " default"

on:
  push:
    paths-ignore:
    - '*.md'
    branches:
    - '**'

jobs:
  # ensure all the basic pre-commit checks pass
  check:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: pre-commit
      uses: pre-commit/action@v2.0.3

  # test the code
  test:
    needs: check
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: init-go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: test
      run: make test

  tag:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: release
      id: bump_semver
      uses: superblocksteam/github-tag-action@1.39.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true

  release:
    needs: tag
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Unshallow
      run: git fetch --prune --unshallow
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    
    - name: Import GPG key
      id: import_gpg
      uses: crazy-max/ghaction-import-gpg@v5
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
    
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2.8.0
      with:
        version: latest
        args: release --rm-dist
      env:
        GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}